### PR TITLE
AMPLIFIED level-type and hidden pass by default 

### PR DESCRIPTION
**Pull request by KirillEsipov**
AMPLIFIED level-type and hidden pass by default

### CODE REVIEW

**Comment by Siliconheart** [comment]
Привет Кирилл!
Амплифаед левел-тайп это хорошо, а вот скрытый пароль ты зря в один запрос запихал. Много было копий сломано в холиварах про этот пункт. Подробнее тут - #20 Так что если хочешь чтобы Виллиам принял твои правки, создай отдельный ПР только с добавлением амплифаед.

**Comment by hexparrot** [comment]
As @Siliconheart stated, there is some contention about the change of password masking. If you're interested in having the new level-type option included, are you able to do so in a PR addressing that singular issue?

**Comment by hexparrot** [comment]
I have added AMPLIFIED (and also CUSTOMIZED) as options for level-type.

I appreciate your pull request, and in the future I will be able to pull your updates in, but try to make on PR per issue addressed.

**Comment by KirillEsipov** [comment]
THX & sorry for long respond. First of all i was trying find way to remove commits from PR. And then I realize, there is only one way to do it by complete deleting of repo, and make all completely from the ground.

**Comment by hexparrot** [comment]
Alternatively--and I just learned this myself--just add on to your PR a commit that reverts the unwanted commits.  Sure, it adds two entries to the history, but it will still at least reflect your contributions.

**Pull request closed without merging**
